### ISSUE TITLE
Add nightly warning

### ISSUE THREAD

**Issue by ghost** [dmitmel/sorting-visualization#1]
The code uses `#![feature]`, which is nightly-only.

Maybe it should be mentionned somewhere?

**Comment by dmitmel** [comment]
Thanks for reporting! I've already removed nightly features in [ae3138c](https://github.com/dmitmel/sorting-visualization/commit/ae3138cd6789e8d101f8e6f3f8cce0e84e98668b) and added a notice about building docs to the README in [51a13df](https://github.com/dmitmel/sorting-visualization/commit/51a13dfdf08aff017be3c529e206c119468747bf). I guess this issue can be closed now.
